comp_wb_pkg:
	vlog $(ECE745_PROJECT_HOME)/verification_ip/interface_packages/wb_pkg/src/wb_if.sv

comp_clk_pkg:
	vlog $(ECE745_PROJECT_HOME)/verification_ip/interface_packages/wb_pkg/src/clk_gen.sv

comp_rst_pkg:
	vlog $(ECE745_PROJECT_HOME)/verification_ip/interface_packages/wb_pkg/src/rst_gen.sv
