

comp_i2cmb_env_pkg:

	vlog +incdir+$(ECE745_COMMON_HOME)/ncsu_pkg $(ECE745_COMMON_HOME)/ncsu_pkg/ncsu_pkg.sv
	vlog +incdir+$(ECE745_COMMON_HOME)/ncsu_pkg $(ECE745_PROJECT_HOME)/verification_ip/interface_packages/wb_pkg/wb_pkg.sv
	vlog +incdir+$(ECE745_COMMON_HOME)/ncsu_pkg $(ECE745_PROJECT_HOME)/verification_ip/interface_packages/i2c_pkg/i2c_pkg.sv
	vlog +incdir+$(ECE745_COMMON_HOME)/ncsu_pkg $(ECE745_PROJECT_HOME)/verification_ip/environment_packages/i2cmb_env_pkg/i2cmb_env_pkg.sv
